ROLES = [
    ("ROLE_SUPER_ADMIN", "super_admin"),
    ("ROLE_ADMIN", "admin"),
    ("ROLE_MANAGER", "Manager"),
    ("ROLE_TECHNICIEN", "Technicien"),
    ("ROLE_ANONYME", "Anonyme"),
]


ROLE_ADMIN_HERITED = ["ROLE_SUPER_ADMIN", "ROLE_ADMIN"]

ROLE_OWNER_HERITED = ["ROLE_SUPER_ADMIN", "ROLE_ADMIN", "ROLE_MANAGER"]

ROLE_MANAGER = ["ROLE_MANAGER",  "ROLE_ADMIN",
                "ROLE_TECHNICIEN"]

ROLE_SUPERVISOR = ["ROLE_MANAGER", "ROLE_SUPERVISOR"]


DATE_FORMAT = "%Y-%m-%d"

NUMBER_MAX_ACCOUNT = 5
