# Generated by Django 5.2.1 on 2025-06-16 19:28

import authentification.models
import authentification.validators
import datetime
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
import helpers.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(default='John', max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(default='Does', max_length=150, verbose_name='last name')),
                ('role_name', models.CharField(choices=[('ROLE_SUPER_ADMIN', 'super_admin'), ('ROLE_ADMIN', 'admin'), ('ROLE_MANAGER', 'Manager'), ('ROLE_SUPERVISOR', 'Superviseur'), ('ROLE_TECHNICIEN', 'Technicien'), ('ROLE_ANONYME', 'Anonyme')], default='ROLE_ANONYME', max_length=150, verbose_name='role name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('region', models.JSONField(default=authentification.models.User.region_default, max_length=10, validators=[authentification.validators.validate_region])),
                ('added_by', models.CharField(blank=True, max_length=150)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_joined')),
                ('email_verified', models.BooleanField(default=False, help_text='Designates whether this user email is verified. ', verbose_name='email_verified')),
                ('limited_access_date', models.DateField(default=datetime.date(2025, 9, 14))),
                ('occupation', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=authentification.models.User.get_file_path, validators=[helpers.validator.validate_file_size, django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('first_contact', models.IntegerField(blank=True, null=True, validators=[helpers.validator.validate_contact])),
                ('second_contact', models.IntegerField(blank=True, null=True, validators=[helpers.validator.validate_contact])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            managers=[
                ('objects', authentification.models.MyUserManager()),
            ],
        ),
    ]
