# Generated by Django 5.2.1 on 2026-02-23 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='limited_access_date',
            field=models.DateField(default=datetime.date(2026, 5, 24)),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_name',
            field=models.CharField(choices=[('ROLE_SUPER_ADMIN', 'super_admin'), ('ROLE_ADMIN', 'admin'), ('ROLE_MANAGER', 'Manager'), ('ROLE_SUPERVISOR', 'Superviseur'), ('ROLE_TECHNICIEN', 'Technicien'), ('ROLE_STORE_KEEPER', 'Magasinier'), ('ROLE_MAINTAINER', 'Maintenancier'), ('ROLE_ANONYME', 'Anonyme')], default='ROLE_ANONYME', max_length=150, verbose_name='role name'),
        ),
    ]
