# Generated by Django 6.0.4 on 2026-05-03 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_user_limited_access_date_alter_user_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='limited_access_date',
            field=models.DateField(default=datetime.date(2026, 8, 1)),
        ),
    ]
